import { MenuItem, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'mains', name: 'Mains' },
  { id: 'burgers', name: 'Burgers' },
  { id: 'combos', name: "Lunch/Dinner Combo's" },
  { id: 'salads', name: 'Salads' },
  { id: 'sandwiches', name: 'Sandwiches' },
  { id: 'pasta', name: 'Pasta Lovers' },
  { id: 'drinks', name: 'Drinks' },
];

export const MENU_ITEMS: MenuItem[] = [
  // MAINS
  {
    id: 'm1',
    name: 'Beef Tenderloin',
    description: 'Marinated grilled beef tenderloin, served on top of creamy mashed potato',
    price: 1160,
    category: 'mains',
  },
  {
    id: 'm2',
    name: 'Beef Stroganoff',
    description: 'Thinly sliced beef stew with onion, mushroom and crème sauce served with rice',
    price: 909,
    category: 'mains',
  },
  {
    id: 'm3',
    name: 'Golden Blue Beef',
    description: 'Mashed potato topped with golden grilled meat, malted cheese, melted cheese.. spinach, mushrooms',
    price: 900,
    category: 'mains',
  },
  {
    id: 'm4',
    name: 'Tuscan Chicken',
    description: 'Grilled seasoned chicken breast simmered with cream sauce, spinach and cherry tomato served with mashed potato',
    price: 1217,
    category: 'mains',
  },
  {
    id: 'm5',
    name: 'Grilled Chicken',
    description: 'Grilled seasoned chicken breast served with rice and mashed potato',
    price: 1162,
    category: 'mains',
  },
  {
    id: 'm6',
    name: 'Chicken Fried Rice',
    description: 'Pan fried chicken breast served with fired rice',
    price: 980,
    category: 'mains',
  },
  {
    id: 'm7',
    name: 'Butter Lemon Chicken',
    description: 'Grilled chicken breast with house butter lemon spicy sauce cooked with mix vegetable served with mashed potato',
    price: 1229,
    category: 'mains',
  },
  {
    id: 'm8',
    name: 'Fried Chicken Legs',
    description: 'Fried breaded chicken leg, bbq sauce side French fries',
    price: 857,
    category: 'mains',
  },
  {
    id: 'm9',
    name: 'Chicken Wings',
    description: 'Breaded chicken wings, bbq sauce, mixed spices side choice rice or French fries',
    price: 852,
    category: 'mains',
  },
  {
    id: 'm10',
    name: 'Butter Lemon Fish',
    description: 'Grilled Fish with house butter lemon spicy sauce cooked with mix vegetable served with mashed potato',
    price: 1117,
    category: 'mains',
  },
  {
    id: 'm11',
    name: 'Fish Gulash',
    description: 'Breaded Nile Perch fish cooked with tomato, onion and pepper served with vegetable rice',
    price: 907,
    category: 'mains',
    isFasting: true,
  },
  {
    id: 'm12',
    name: 'Fish Cutlets',
    description: 'Fried Nile Perch served with vegetable rice',
    price: 916,
    category: 'mains',
    isFasting: true,
  },
  {
    id: 'm13',
    name: 'Fish and Chips',
    description: 'Breaded Fish served with french fries, ketchup, mayo and cheese sauce',
    price: 987,
    category: 'mains',
    isFasting: true,
  },
  {
    id: 'm14',
    name: 'Eggplant Caponata',
    description: 'Eggplant cooked with juicy tomato sauce, onion and pepper served with vegetable rice',
    price: 610,
    category: 'mains',
    isFasting: true,
  },

  // BURGERS
  {
    id: 'b1',
    name: 'House Beef Burger',
    description: 'In house made bun filled with beef patty, house sauce, caramelized onion, cheese served with fries',
    price: 772,
    category: 'burgers',
  },
  {
    id: 'b2',
    name: 'BBQ Beef Burger',
    description: 'In house made bun filled with beef patty, BBQ sauce, cheese, lettuce, pickles served with fries',
    price: 734,
    category: 'burgers',
  },
  {
    id: 'b3',
    name: 'Crispy Chicken Burger',
    description: 'In house made bun filled with crispy chicken patty, mayo sauce, cheese, lettuce, tomato served with fries',
    price: 845,
    category: 'burgers',
  },
  {
    id: 'b4',
    name: 'Cheese Burger',
    description: 'In house made bun filled with beef patty, mayo sauce, cheese, lettuce, tomato served with fries',
    price: 796,
    category: 'burgers',
  },

  // COMBOS
  {
    id: 'c1',
    name: 'Fasting Combo 1',
    description: 'Choice of falafel or nile perch fish, choice of mixed salad or french fries, choice of aryabhata or tomato sauce pasta served with toasted bread',
    price: 1020,
    category: 'combos',
    isFasting: true,
  },

  // SALADS
  {
    id: 's1',
    name: 'Garden Salad',
    description: 'Mix of lettuce, shredded carrot, onion with garden dressing served with toasted bread',
    price: 456,
    category: 'salads',
  },
  {
    id: 's2',
    name: 'Avocado Salad',
    description: 'Mix of lettuce, shredded carrot, onion with garden dressing served with toasted bread',
    price: 468,
    category: 'salads',
  },
  {
    id: 's3',
    name: 'Green Salad',
    description: 'Mix of lettuce, cucumber, tomato, onion and avocado dressing',
    price: 468,
    category: 'salads',
  },
  {
    id: 's4',
    name: 'Tuna Salad',
    description: 'Mix of lettuce shredded carrot, onion and Tuna with garden dressing served with toasted bread',
    price: 610,
    category: 'salads',
    isFasting: true,
  },
  {
    id: 's5',
    name: 'Cesar Salad',
    description: 'Lettuce, bread crumbs, Chicken with Cesar dressing served with toasted bread',
    price: 728,
    category: 'salads',
  },

  // SANDWICHES
  {
    id: 'sw1',
    name: 'Philly Cheese Steak',
    description: 'Sliced pieces of beef steak, melted cheese, mayonnaise, with caramelized onion served with french fries with choice of brown or white bread',
    price: 854,
    category: 'sandwiches',
  },
  {
    id: 'sw2',
    name: 'Philly Cheese Chicken',
    description: 'Sliced pieces of chicken and melted cheese mayonnaise, with caramelized onion served with french fries with choice of brown or white bread',
    price: 827,
    category: 'sandwiches',
  },
  {
    id: 'sw3',
    name: 'Chicken Crispy Wrap',
    description: 'Pita wrapped breaded chicken tenders with house sauce, cheese & served with french fries',
    price: 837,
    category: 'sandwiches',
  },
  {
    id: 'sw4',
    name: 'Fish Crispy Wrap',
    description: 'Pita wrapped breaded fish with house sauce served with french fries',
    price: 800,
    category: 'sandwiches',
    isFasting: true,
  },
  {
    id: 'sw5',
    name: 'Tuna Fajita Wrap',
    description: 'Pita wrapped Tuna cooked in a fajita style served with french fries',
    price: 710,
    category: 'sandwiches',
    isFasting: true,
  },
  {
    id: 'sw6',
    name: 'Tuna Sandwich',
    description: 'Tuna sandwich mixed in sauce, onion, tomato & pepper served with french fries with choice of brown or white bread',
    price: 632,
    category: 'sandwiches',
    isFasting: true,
  },
  {
    id: 'sw7',
    name: 'Avocado Vegan Wrap',
    description: 'Pita wrapped avocado, onion, tomato mixed in house sauce served with french fries',
    price: 544,
    category: 'sandwiches',
    isFasting: true,
  },
  {
    id: 'sw8',
    name: 'Veggie Sandwich',
    description: 'Carrots, zucchini, cauliflower, broccoli, pesto, mix spices side organic potatoes',
    price: 430,
    category: 'sandwiches',
    isFasting: true,
  },

  // PASTA
  {
    id: 'p1',
    name: 'Ravioli',
    description: 'House made ravioli staffed with spinach and ricotta cheese served with choice of tomato, pesto, white or bologna sauce',
    price: 720,
    category: 'pasta',
  },
  {
    id: 'p2',
    name: 'Chicken Alfredo',
    description: 'Creamy white sauce made with butter, fresh cream, cooked with chicken tossed with choice of spaghetti or penne',
    price: 849,
    category: 'pasta',
  },
  {
    id: 'p3',
    name: 'Pasta Bolognese',
    description: 'Tomato sauce cooked with minced meat, onion and fresh herbs tossed with choice of spaghetti or penne',
    price: 849,
    category: 'pasta',
  },
  {
    id: 'p4',
    name: 'Chicken Pesto',
    description: 'Creamy pesto sauce made with butter, fresh cream and cheese cooked with chicken tossed with choice of spaghetti or penne',
    price: 899,
    category: 'pasta',
  },
  {
    id: 'p5',
    name: 'Pesto Pasta',
    description: 'Pesto sauce cooked with herbs tossed with choice of spaghetti or penne',
    price: 700,
    category: 'pasta',
  },
  {
    id: 'p6',
    name: 'Pasta Aryabhata',
    description: 'Spicy tomato sauce tossed with choice of spaghetti or penne',
    price: 598,
    category: 'pasta',
    isFasting: true,
  },
  {
    id: 'p7',
    name: 'Tomato Sauce Pasta',
    description: 'Tomato sauce cooked with herbs tossed with choice of spaghetti or penne',
    price: 590,
    category: 'pasta',
    isFasting: true,
  },

  // DRINKS
  {
    id: 'd1',
    name: 'Soda',
    description: 'Refreshing carbonated soft drink of your choice',
    price: 45,
    category: 'drinks',
  },
  {
    id: 'd2',
    name: 'Mineral Water',
    description: 'Local sparkling or still mineral water',
    price: 35,
    category: 'drinks',
    isFasting: true,
  },
  {
    id: 'd3',
    name: 'Coffee',
    description: 'Traditional Ethiopian bean coffee, freshly roasted',
    price: 40,
    category: 'drinks',
    isFasting: true,
  },
  {
    id: 'd4',
    name: 'Tea',
    description: 'Aromatic black tea with local spices',
    price: 30,
    category: 'drinks',
    isFasting: true,
  },
  {
    id: 'd5',
    name: 'Macchiato',
    description: 'Rich espresso topped with a small amount of foamed milk',
    price: 55,
    category: 'drinks',
  },
];
